import type { Metadata } from "next";
import "@/style/globals.css";
import { Noto_Sans_SC } from "next/font/google";
import { Header } from "./Header";
import { Footer } from "./Footer";
import { Provider } from "jotai";
import { cn } from "@/lib/utils";
import ThemeProvider from "@/components/ThemeProvider";

const notoSansSC = Noto_Sans_SC({
  variable: "--font-noto-sans-sc",
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${notoSansSC.variable} scroll-smooth`}>
      <body>
        <Provider>
          <ThemeProvider>
            <section
              className={cn(
                "flex min-h-screen flex-col max-sm:justify-center max-sm:items-center px-20  bg-neutral-100 dark:bg-neutral-800 "
              )}
            >
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
            </section>
          </ThemeProvider>
        </Provider>
      </body>
    </html>
  );
}
