import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/style/globals.css";
import { Header } from "./Header";
import { Footer } from "./Footer";
import { Provider } from "jotai";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="container mx-auto px-4 flex min-h-screen flex-col bg-neutral-100 ">
        <Provider>
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
